Release workflow updates loosely converted to TypeScript
pubpub/pubpub pull request #1030
Opened 2020-09-08 17:06 UTC by 3mcd

This PR contains all the fixes @djagdish introduced in #1023, rebased on latest master, with each affected change "rewritten" in TypeScript.

Test Plan:
- Verify this code works exactly the same as #1023.

2020-09-09 20:01 UTC, idreyn requested changes
Great usability improvements here! My feedback is mostly on cosmetic issues, and this should be good to go after a look at some of this stuff relating to copy, icons, padding, and a few questions about CSS structure.

Not sure if I am addressing this at @3mcd or @djagdish here — in fact, I would be happy to go through and make these changes myself with your combined blessing.

2020-09-09 20:28 UTC, 3mcd commented on client/components/PubReleaseDialog/PubReleaseDialog.tsx
> +		releases?: { createdAt?: string }[];
Ah, I wasn't aware that's how PropTypes worked. I was under the impression that in the above example, `releases` would still be optional unless you tacked an `isRequired` on the end.

2020-09-09 20:33 UTC, 3mcd commented on client/components/PubReleaseDialog/PubReleaseDialog.tsx
> +					{' The previous Release ('}
I think we should be able to omit the bracket/quotations from this line (and line 118).

2020-09-09 20:36 UTC, 3mcd commented
@idreyn FWIW you have my go-ahead to make any proposed changes, although I can't speak for @djagdish, since most of the suggestions are related to his code!

2020-09-09 20:36 UTC, idreyn commented on client/components/PubReleaseDialog/PubReleaseDialog.tsx
> +		releases?: { createdAt?: string }[];
Honestly I think you're right, and my mental model of PropTypes is broken!

2020-09-16 15:34 UTC, 3mcd commented
I went ahead and knocked out everything but your $0.02 items for now, @idreyn!

2020-09-16 15:47 UTC, 3mcd commented on client/components/PubReleaseDialog/PubReleaseDialog.tsx
> +					Return to Draft
I'm gonna consider this a $0.02 item for now.

2020-09-16 16:22 UTC, merged