update: Add a popover to prevent accidental block removal
pubpub/pubpub pull request #1489
Opened 2021-06-24 22:10 UTC by qweliant

Resolves #651 

This update addresses accidental block deletion. When removing a block, it can be easy to accidentally delete another one because of how fast the block removal happens. It can also be easy to accidentally delete a block when you are not trying to. 

old block removal
<img width="326" alt="Screen Shot 2021-06-24 at 6 09 34 PM" src="https://user-images.githubusercontent.com/34730449/123338740-5f041800-d517-11eb-8101-ce5d902fadc9.png">

updated block removal
<img width="379" alt="Screen Shot 2021-06-24 at 5 48 50 PM" src="https://user-images.githubusercontent.com/34730449/123337593-7215e880-d515-11eb-8093-d61a46cca1dc.png">

<img width="345" alt="Screen Shot 2021-06-24 at 5 55 34 PM" src="https://user-images.githubusercontent.com/34730449/123337577-6b877100-d515-11eb-9e5f-4930baa617d2.png">

testing plan:
test for different screen sizes 
make sure the blocks are actually removed

2021-06-24 22:19 UTC, qweliant commented
would a red remove button be better or outside? similar to the page deletion button?

2021-06-25 15:00 UTC, idreyn requested changes
Substantially this looks great — the only thing that needs to be changed is the `aria-label` on the Popover. Nice work!

2021-06-25 20:09 UTC, qweliant commented on client/components/LayoutEditor/LayoutEditor.tsx
> +											<Button
mmm, i can taste the fear now

2021-06-28 20:38 UTC, idreyn approved these changes
LGTM!

2021-06-28 20:56 UTC, merged