fix: more robust community check to avoid impersonation, phishing, and other hacks
pubpub/pubpub pull request #1503
Opened 2021-07-09 15:05 UTC by qweliant

This fix addresses an issue where bad actors can impersonate members of communities they are not apart of. We now verify that a user has contributed to a community.

2021-07-13 22:56 UTC, idreyn requested changes
Functionally looks great, requested changes are pretty much all cosmetic. Nice work!

2021-07-13 22:56 UTC, idreyn commented on server/community/__tests__/queries.test.ts
> +// 1. User is Member of Community => true
Let's remove these!

2021-07-13 22:56 UTC, idreyn commented on server/community/__tests__/queries.test.ts
> +// i dont get how to access stuff but he said it wasnt a tree so maybe just directlt cause userId is on pub maybe
This too

2021-07-13 22:56 UTC, idreyn commented on server/community/queries.ts
> +export const getCountOfPubsOrCollections = async (userId: string, communityId: string) => {
A name that better describes what this does might be `isUserAffiliatedWithCommunity`

2021-07-13 22:56 UTC, idreyn commented on server/community/queries.ts
> +	// indicates if user is present
Probably okay to (1) remove this comment and (2) return the `counts.some(...)` value directly without an intermediate variable.

2021-07-13 22:56 UTC, idreyn commented on server/routes/user.tsx
> +// check if member has any pubs or collections for user
This comment has come detached from the function it describes — probably best to remove it.

2021-07-13 22:56 UTC, idreyn commented on server/routes/user.tsx
> +		const isThisUserAPartOfThisCOmmunity = await getCountOfPubsOrCollections(
Spare capital O here

2021-07-21 19:12 UTC, qweliant reviewed
made changes and ready for another review

2021-07-22 16:16 UTC, idreyn approved these changes
LGTM, nice work!

2021-07-22 18:29 UTC, merged