Send `PubSyncManager` softly into that good night
pubpub/pubpub pull request #1867
Opened 2022-03-15 21:02 UTC by idreyn

2022-05-12 08:04 UTC, howebenhowe requested changes
Code looks great, much simplified, and more familiar pattern of how we hook elsewhere. Great work!

Testing results:
+ I took 'deep link into draft' to mean copying the link to node from the draft pub body. The link copied lacked the 'draft' part of the url, pointing instead to the most recently released version. Linking from release worked great.
+ consistent with master, turns out, but archiving a discussion leaves interactive visual residue of the discussion. I assume that's not desired?
![Screenshot from 2022-05-12 03-48-41](https://user-images.githubusercontent.com/14115194/168021512-42e28c9e-58b2-4a06-9a3c-cd92e113f438.png)
+ 'archive' option is available on still-empty discussions. Using the option triggers 500 err and visually an infinite spin. Actually, there's a couple buggy behaviors there. I shall document them in separate issues.

All other testing came back clean.

2022-05-16 16:58 UTC, idreyn commented
> I took 'deep link into draft' to mean copying the link to node from the draft pub body. The link copied lacked the 'draft' part of the url, pointing instead to the most recently released version. Linking from release worked great.

@howebenhowe this is something we changed intentionally in #1985 because people wanted to create intra-Pub links that still work when you release the Pub, and including `/draft` in the URL breaks that. (Come to think of it, we should probably just strip the Pub URL out altogether in that case, but not sure what the UX should be).

By "deep linking" in the test plan it turns out I meant the "permalinking" functionality provided by this button:

![image](https://user-images.githubusercontent.com/2208769/168644774-44a9ebca-c394-43e3-9302-f45dcae31a8c.png)

which should continue to link directly into the draft.

2022-05-16 17:07 UTC, idreyn commented on client/components/TimeAgo/TimeAgo.tsx
> +		useDateCutoffDays = 7,
I don't know...it predates both me and the concept of React hooks because I raise an eyebrow every time I see it.

2022-05-16 17:09 UTC, idreyn commented on client/containers/Pub/PubDocument/PubBody.tsx
> +		'Your Pub has changes that are still unsaved. Are you sure you wish to leave?',
Hmm...I like the simplicity, but if I let my mind glaze over and try to read this from the perspective of an unseasoned user, I might think that there's something that I have to do to save the Pub other than wait.

2022-05-16 17:43 UTC, idreyn commented on client/containers/Pub/Pub.tsx
> +	return <PubSuspendWhileTyping delay={1000}>{() => <HeaderComponent />}</PubSuspendWhileTyping>;
(We talked about this on Slack and it turns out that Eric is right here, but the bigger issue is that `PubSuspendWhileTyping` is not really doing its job anymore — it relies on `React.memo` which ignores the `useContext()` hooks we're using all over the place to get Pub state from `usePubContext`. The right move is probably to move the "suspend while typing" functionality into `usePubContext()`.

2022-05-23 21:00 UTC, howebenhowe approved these changes
Last commit looking good.

2022-05-23 21:02 UTC, howebenhowe commented on server/pubHistory/permissions.ts
> -export const getPermissions = async ({ userId, communityId, pubId, accessHash, historyKey }) => {
That makes sense. I figured either the previous version was confused when it included two ids or the present was confused when it dropped one of them.

2022-05-23 21:06 UTC, howebenhowe commented
@idreyn looking good across the board. I wonder who set up what 'permalink' means, and who defends that meaning through time so it doesn't slip around.

I am excited to benefit from this feature.

2022-05-24 14:58 UTC, merged