Controls Link Enhancement
pubpub/pubpub pull request #2615
Opened 2023-04-19 12:18 UTC by qweliant

## Issue(s) Resolved
solves #2498 #2607 

## Test Plan
Run your dev server 

For the next part:
Use a link to a pub ( from demo.duqduq )
Use a link to a DOI or an actual DOI  ( https://arxiv.org/pdf/2304.00353.pdf, https://doi.org/10.48550/arXiv.2304.00353 )
Use a link to some random site (https://blueprintjs.com/)
*use each 

create a link in a pub document
set a connection ( use different relationships and/ or directions for each link )
save a connection

be sure the attributions and metadata for link is correct
be sure a new collection edge appears in the pub 
be sure the collection has the correct relationship and direction

reload the page, be sure the connection is present with "create connection still selected"
update the direction and/or relationship
be sure the changes persist

remove a connection from the link modal
be sure it is removed from the pub document and dashboard

remove a connection from the dashboard
be sure it is removed in the pub document 
be sure 'Create Connection' is not checked

## Screenshots (if applicable)

### Notes/Context/Gotchas

edges with a direction away from the pub do not update in realtime 

### Supporting Docs
https://notes.knowledgefutures.org/pub/kz8y3bt6/release/2

2023-04-20 12:14 UTC, 3mcd commented on client/components/FormattingBar/controlComponents/ControlsLink.tsx
> +		setIsLoadingAttr(true);
Was this necessary to get the attribute to update in the DOM? If not, we might be able to remove this state.

2023-04-20 12:22 UTC, 3mcd requested changes
Code looks great, but I think we need to spend a little more time with it because I found a few issues when testing.

When creating a connection to an external publication like so:
![image](https://user-images.githubusercontent.com/6402908/233361516-6941fcb3-14fa-4d6e-a6ad-82e78c440d70.png)

I get the following error:

![image](https://user-images.githubusercontent.com/6402908/233361778-96aacc61-3412-4d35-a3ce-b15021377ed0.png)

Connection creation did work for a Pub URL, but when I clicked "Save connection", the new connection didn't show up in the Pub. The connection _had_ been created in the dashboard, but when I reloaded the page, the link did not have a connection tied to it.

After I deleted the link (and connections) to get a clean slate, I tried to add a connection to the same Pub through a link. The previous issue happened again, so I clicked "Save connection" another time. The connection still did not show up at the bottom of the Pub, and the connections looked like this in the dashboard:
![image](https://user-images.githubusercontent.com/6402908/233363797-641137b5-914f-460f-99d8-32391eafe014.png)

2023-04-24 19:32 UTC, qweliant commented on client/components/FormattingBar/controlComponents/ControlsLink.tsx
> +					onClick={activeLink.removeLink}
The onclick for this should remove the connection as well. May not be important just yet but a quick add on to this should be alright

2023-04-25 20:30 UTC, 3mcd approved these changes
LGTM!

2023-04-25 21:07 UTC, merged